'use client';

import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import {
  Box,
  Container,
  Typography,
  Button,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Chip,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  MenuItem,
  Stack,
  CircularProgress,
  Alert,
} from '@mui/material';
import {
  Add as AddIcon,
  Visibility as ViewIcon,
  Description as DescriptionIcon,
} from '@mui/icons-material';

import { claimApi } from '@/services/claim.service';
import { warrantyApi } from '@/services/warranty.service';
import { Claim } from '@/types/claim.types';
import { Warranty } from '@/types/warranty.types';

export default function ClaimsPage() {
  const queryClient = useQueryClient();
  const [showAddForm, setShowAddForm] = useState(false);
  const [formData, setFormData] = useState({
    warrantyId: 0,
    issueDescription: '',
    resolutionDetails: ''
  });

  // Fetch claims
  const { data: claims = [], isLoading: claimsLoading } = useQuery({
    queryKey: ['claims'],
    queryFn: claimApi.getUserClaims,
  });

  // Fetch warranties
  const { data: warranties = [], isLoading: warrantiesLoading } = useQuery({
    queryKey: ['warranties'],
    queryFn: warrantyApi.getUserWarranties,
  });

  // Create claim mutation
  const { mutate: createClaim, isPending: isCreating } = useMutation({
    mutationFn: claimApi.createClaim,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['claims'] });
      setShowAddForm(false);
      setFormData({
        warrantyId: 0,
        issueDescription: '',
        resolutionDetails: ''
      });
    },
    onError: (error: any) => {
      console.error('Error creating claim:', error);
    }
  });

  // Handle form submission
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const selectedWarranty = warranties.find(w => w.id === formData.warrantyId);
    if (!selectedWarranty) return;

    createClaim({
      issueDescription: formData.issueDescription,
      resolutionDetails: formData.resolutionDetails,
      status: 'PENDING' as const,
      referenceNumber: '', // Generated by backend
      warranty: selectedWarranty
    });
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'PENDING':
        return 'warning';
      case 'APPROVED':
        return 'success';
      case 'RESOLVED':
        return 'info';
      case 'REJECTED':
        return 'error';
      default:
        return 'default';
    }
  };

  return (
    <Box sx={{ flexGrow: 1, py: 3 }}>
      <Container maxWidth="xl">
        <Stack spacing={3}>
          {/* Header */}
          <Stack direction="row" alignItems="center" justifyContent="space-between" spacing={2}>
            <Box>
              <Typography variant="h4" component="h1" gutterBottom>
                My Claims
              </Typography>
              <Typography color="text.secondary" variant="body1">
                Submit and track your warranty claims
              </Typography>
            </Box>
            <Button
              variant="contained"
              startIcon={<AddIcon />}
              onClick={() => setShowAddForm(true)}
              size="large"
            >
              Submit Claim
            </Button>
          </Stack>

          {/* Error Alert */}
          {claimsLoading && (
            <Alert severity="info" sx={{ mb: 2 }}>
              Loading claims...
            </Alert>
          )}

          {/* Claims Table */}
          <Paper sx={{ width: '100%', overflow: 'hidden' }}>
            <TableContainer sx={{ maxHeight: 600 }}>
              <Table stickyHeader>
                <TableHead>
                  <TableRow>
                    <TableCell sx={{ fontWeight: 'bold' }}>Reference</TableCell>
                    <TableCell sx={{ fontWeight: 'bold' }}>Product</TableCell>
                    <TableCell sx={{ fontWeight: 'bold' }}>Issue</TableCell>
                    <TableCell sx={{ fontWeight: 'bold' }}>Status</TableCell>
                    <TableCell sx={{ fontWeight: 'bold' }}>Submitted</TableCell>
                    <TableCell sx={{ fontWeight: 'bold' }}>Actions</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {claims.length === 0 ? (
                    <TableRow>
                      <TableCell colSpan={5} align="center" sx={{ py: 8 }}>
                        <Stack alignItems="center" spacing={2}>
                          <DescriptionIcon sx={{ fontSize: 48, color: 'text.secondary' }} />
                          <Typography variant="h6" color="text.secondary">
                            No claims submitted
                          </Typography>
                          <Typography variant="body2" color="text.secondary" sx={{ textAlign: 'center' }}>
                            Get started by submitting your first warranty claim.
                          </Typography>
                          <Button
                            variant="contained"
                            startIcon={<AddIcon />}
                            onClick={() => setShowAddForm(true)}
                            sx={{ mt: 2 }}
                          >
                            Submit Claim
                          </Button>
                        </Stack>
                      </TableCell>
                    </TableRow>
                  ) : (
                    claims.map((claim) => (
                      <TableRow key={claim.id} hover>
                        <TableCell>
                          <Typography variant="body2" sx={{ fontFamily: 'monospace' }}>
                            {claim.referenceNumber}
                          </Typography>
                        </TableCell>
                        <TableCell>
                          <Box>
                            <Typography variant="body2" sx={{ fontWeight: 'medium' }}>
                              {claim.warranty.userProduct.product.name}
                            </Typography>
                            <Typography variant="caption" color="text.secondary">
                              S/N: {claim.warranty.userProduct.serialNumber}
                            </Typography>
                          </Box>
                        </TableCell>
                        <TableCell>
                          <Box sx={{ maxWidth: 200 }}>
                            <Typography variant="body2" noWrap>
                              {claim.issueDescription}
                            </Typography>
                          </Box>
                        </TableCell>
                        <TableCell>
                          <Chip
                            label={claim.status}
                            color={getStatusColor(claim.status)}
                            size="small"
                          />
                        </TableCell>
                        <TableCell>
                          {new Date(claim.createdAt).toLocaleDateString()}
                        </TableCell>
                        <TableCell>
                          <IconButton size="small" color="primary">
                            <ViewIcon />
                          </IconButton>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </TableContainer>
          </Paper>
        </Stack>

        {/* Add Claim Dialog */}
        <Dialog
          open={showAddForm}
          onClose={() => setShowAddForm(false)}
          maxWidth="md"
          fullWidth
          PaperProps={{ sx: { maxHeight: '90vh' } }}
        >
          <DialogTitle>Submit New Claim</DialogTitle>
          <form onSubmit={handleSubmit}>
            <DialogContent>
              <Stack spacing={3} sx={{ mt: 1 }}>
                <TextField
                  select
                  fullWidth
                  label="Warranty"
                  value={formData.warrantyId}
                  onChange={(e) => setFormData({ ...formData, warrantyId: parseInt(e.target.value) })}
                  required
                  disabled={warrantiesLoading}
                >
                  <MenuItem value="">Select a warranty</MenuItem>
                  {warranties
                    .filter(w => w.status === 'ACTIVE')
                    .map(warranty => (
                      <MenuItem key={warranty.id} value={warranty.id}>
                        {warranty.userProduct.product.name} - {warranty.userProduct.serialNumber}
                      </MenuItem>
                    ))}
                </TextField>

                <TextField
                  fullWidth
                  label="Issue Description"
                  multiline
                  rows={4}
                  value={formData.issueDescription}
                  onChange={(e) => setFormData({ ...formData, issueDescription: e.target.value })}
                  required
                />

                <TextField
                  fullWidth
                  label="Resolution Details (Optional)"
                  multiline
                  rows={3}
                  value={formData.resolutionDetails}
                  onChange={(e) => setFormData({ ...formData, resolutionDetails: e.target.value })}
                />
              </Stack>
            </DialogContent>
            <DialogActions sx={{ p: 3 }}>
              <Button onClick={() => setShowAddForm(false)}>
                Cancel
              </Button>
              <Button
                type="submit"
                variant="contained"
                disabled={isCreating}
                startIcon={isCreating ? <CircularProgress size={20} /> : null}
              >
                {isCreating ? 'Submitting...' : 'Submit Claim'}
              </Button>
            </DialogActions>
          </form>
        </Dialog>
      </Container>
    </Box>
  );
}
