import type { ClaimContact } from '../src/app/core/models/claim-contact.model';

/** Generic manufacturer claim guidance used across brand entries. */
function manufacturerSteps(provider: string): string[] {
  return [
    'Locate your proof of purchase and the product serial number.',
    `Contact ${provider} support through the link below and describe the issue.`,
    'Follow the repair, replacement, or refund instructions from the service team.',
  ];
}

/** Generic retailer claim guidance used across retailer entries. */
function retailerSteps(retailer: string): string[] {
  return [
    'Gather your receipt, the product serial number, and the original packaging if available.',
    `Contact ${retailer} with the fault details and your purchase date.`,
    'Follow the return, repair, or extended-warranty process advised by the retailer.',
  ];
}

/**
 * Curated claim contacts for every catalog brand and retailer.
 * Managed in the Firebase Console; seeded with `npm run seed:claim-contacts`.
 * Best-effort details: hotlines are omitted where not confidently known.
 */
export const CLAIM_CONTACTS: ClaimContact[] = [
  // Brands (manufacturer)
  {
    type: 'manufacturer',
    name: 'Apple',
    matchKeys: ['apple inc', 'apple computer'],
    url: 'https://support.apple.com/en-sg',
    claimSteps: manufacturerSteps('Apple'),
    serviceCenterUrl: 'https://support.apple.com/en-sg/repair',
    registrationUrl: 'https://support.apple.com/en-sg/register',
  },
  {
    type: 'manufacturer',
    name: 'Samsung',
    matchKeys: ['samsung electronics'],
    url: 'https://www.samsung.com/sg/support/',
    claimSteps: manufacturerSteps('Samsung'),
    serviceCenterUrl: 'https://www.samsung.com/sg/support/service-center/',
    registrationUrl: 'https://www.samsung.com/sg/support/warranty/',
  },
  {
    type: 'manufacturer',
    name: 'Sony',
    matchKeys: ['sony electronics'],
    url: 'https://www.sony.com.sg/electronics/support',
    claimSteps: manufacturerSteps('Sony'),
  },
  {
    type: 'manufacturer',
    name: 'LG',
    matchKeys: ['lg electronics'],
    url: 'https://www.lg.com/sg/support',
    claimSteps: manufacturerSteps('LG'),
  },
  {
    type: 'manufacturer',
    name: 'Panasonic',
    matchKeys: [],
    url: 'https://www.panasonic.com/sg/support.html',
    claimSteps: manufacturerSteps('Panasonic'),
  },
  {
    type: 'manufacturer',
    name: 'Philips',
    matchKeys: [],
    url: 'https://www.philips.com.sg/c-w/support-home.html',
    claimSteps: manufacturerSteps('Philips'),
  },
  {
    type: 'manufacturer',
    name: 'Bosch',
    matchKeys: ['bosch home'],
    url: 'https://www.bosch-home.com.sg/service',
    claimSteps: manufacturerSteps('Bosch'),
  },
  {
    type: 'manufacturer',
    name: 'Dyson',
    matchKeys: [],
    url: 'https://www.dyson.com.sg/support',
    claimSteps: manufacturerSteps('Dyson'),
  },
  {
    type: 'manufacturer',
    name: 'Bose',
    matchKeys: [],
    url: 'https://www.bose.com.sg/support.html',
    claimSteps: manufacturerSteps('Bose'),
  },
  {
    type: 'manufacturer',
    name: 'JBL',
    matchKeys: ['jbl harman'],
    url: 'https://support.jbl.com/',
    claimSteps: manufacturerSteps('JBL'),
  },
  {
    type: 'manufacturer',
    name: 'Canon',
    matchKeys: [],
    url: 'https://www.canon.com.sg/support/',
    claimSteps: manufacturerSteps('Canon'),
  },
  {
    type: 'manufacturer',
    name: 'Nikon',
    matchKeys: [],
    url: 'https://www.nikon.com.sg/service-and-support',
    claimSteps: manufacturerSteps('Nikon'),
  },
  {
    type: 'manufacturer',
    name: 'Fujifilm',
    matchKeys: ['fuji film'],
    url: 'https://www.fujifilm.com/sg/support',
    claimSteps: manufacturerSteps('Fujifilm'),
  },
  {
    type: 'manufacturer',
    name: 'GoPro',
    matchKeys: ['go pro'],
    url: 'https://gopro.com/en/sg/support',
    claimSteps: manufacturerSteps('GoPro'),
  },
  {
    type: 'manufacturer',
    name: 'Garmin',
    matchKeys: [],
    url: 'https://support.garmin.com/en-SG/',
    claimSteps: manufacturerSteps('Garmin'),
  },
  {
    type: 'manufacturer',
    name: 'Fitbit',
    matchKeys: [],
    url: 'https://support.google.com/fitbit',
    claimSteps: manufacturerSteps('Fitbit'),
  },
  {
    type: 'manufacturer',
    name: 'Logitech',
    matchKeys: ['logi'],
    url: 'https://support.logi.com/',
    claimSteps: manufacturerSteps('Logitech'),
  },
  {
    type: 'manufacturer',
    name: 'Razer',
    matchKeys: [],
    url: 'https://www.razer.com/sg-en/support',
    claimSteps: manufacturerSteps('Razer'),
  },
  {
    type: 'manufacturer',
    name: 'Dell',
    matchKeys: [],
    url: 'https://www.dell.com/support/home/en-sg',
    claimSteps: manufacturerSteps('Dell'),
  },
  {
    type: 'manufacturer',
    name: 'HP',
    matchKeys: ['hewlett packard', 'hewlett-packard'],
    url: 'https://support.hp.com/sg-en',
    claimSteps: manufacturerSteps('HP'),
  },
  {
    type: 'manufacturer',
    name: 'Lenovo',
    matchKeys: [],
    url: 'https://www.lenovo.com/sg/en/support',
    claimSteps: manufacturerSteps('Lenovo'),
  },
  {
    type: 'manufacturer',
    name: 'Asus',
    matchKeys: ['asustek'],
    url: 'https://www.asus.com/sg/support/',
    claimSteps: manufacturerSteps('Asus'),
  },
  {
    type: 'manufacturer',
    name: 'Acer',
    matchKeys: [],
    url: 'https://www.acer.com/sg-en/support',
    claimSteps: manufacturerSteps('Acer'),
  },
  {
    type: 'manufacturer',
    name: 'MSI',
    matchKeys: ['micro-star international'],
    url: 'https://www.msi.com/support',
    claimSteps: manufacturerSteps('MSI'),
  },
  {
    type: 'manufacturer',
    name: 'Microsoft',
    matchKeys: ['ms'],
    url: 'https://support.microsoft.com/en-sg',
    claimSteps: manufacturerSteps('Microsoft'),
  },
  {
    type: 'manufacturer',
    name: 'Google',
    matchKeys: ['google store'],
    url: 'https://support.google.com/',
    claimSteps: manufacturerSteps('Google'),
  },
  {
    type: 'manufacturer',
    name: 'Xiaomi',
    matchKeys: ['mi'],
    url: 'https://www.mi.com/sg/support/',
    claimSteps: manufacturerSteps('Xiaomi'),
  },
  {
    type: 'manufacturer',
    name: 'Huawei',
    matchKeys: [],
    url: 'https://consumer.huawei.com/sg/support/',
    claimSteps: manufacturerSteps('Huawei'),
  },
  {
    type: 'manufacturer',
    name: 'Oppo',
    matchKeys: [],
    url: 'https://www.oppo.com/sg/support/',
    claimSteps: manufacturerSteps('Oppo'),
  },
  {
    type: 'manufacturer',
    name: 'Vivo',
    matchKeys: [],
    url: 'https://www.vivo.com/sg/support',
    claimSteps: manufacturerSteps('Vivo'),
  },
  {
    type: 'manufacturer',
    name: 'OnePlus',
    matchKeys: ['one plus'],
    url: 'https://www.oneplus.com/sg/support',
    claimSteps: manufacturerSteps('OnePlus'),
  },
  {
    type: 'manufacturer',
    name: 'Nintendo',
    matchKeys: [],
    url: 'https://www.nintendo.com/en-sg/support/',
    claimSteps: manufacturerSteps('Nintendo'),
  },

  // Retailers
  {
    type: 'retailer',
    name: 'Challenger',
    matchKeys: [],
    url: 'https://www.challenger.com.sg',
    claimSteps: retailerSteps('Challenger'),
  },
  {
    type: 'retailer',
    name: 'Courts',
    matchKeys: ['courts singapore'],
    url: 'https://www.courts.com.sg/customer-service',
    claimSteps: retailerSteps('Courts'),
  },
  {
    type: 'retailer',
    name: 'Harvey Norman',
    matchKeys: ['harveynorman'],
    url: 'https://www.harveynorman.com.sg',
    claimSteps: retailerSteps('Harvey Norman'),
  },
  {
    type: 'retailer',
    name: 'Best Denki',
    matchKeys: ['best denki singapore'],
    url: 'https://www.bestdenki.com.sg',
    claimSteps: retailerSteps('Best Denki'),
  },
  {
    type: 'retailer',
    name: 'Gain City',
    matchKeys: ['gaincity'],
    url: 'https://www.gaincity.com',
    claimSteps: retailerSteps('Gain City'),
  },
  {
    type: 'retailer',
    name: 'Audio House',
    matchKeys: ['audiohouse'],
    url: 'https://www.audiohouse.com.sg',
    claimSteps: retailerSteps('Audio House'),
  },
  {
    type: 'retailer',
    name: 'Parisilk',
    matchKeys: [],
    url: 'https://www.parisilk.com',
    claimSteps: retailerSteps('Parisilk'),
  },
  {
    type: 'retailer',
    name: 'Apple Store',
    matchKeys: ['apple store singapore'],
    url: 'https://www.apple.com/sg/shop',
    claimSteps: retailerSteps('Apple Store'),
  },
  {
    type: 'retailer',
    name: 'iStudio',
    matchKeys: ['istudio'],
    url: 'https://www.istudio.com.sg',
    claimSteps: retailerSteps('iStudio'),
  },
  {
    type: 'retailer',
    name: 'Samsung Experience Store',
    matchKeys: ['samsung store'],
    url: 'https://www.samsung.com/sg/',
    claimSteps: retailerSteps('Samsung Experience Store'),
  },
  {
    type: 'retailer',
    name: 'Sony Store',
    matchKeys: ['sony store singapore'],
    url: 'https://www.sony.com.sg/',
    claimSteps: retailerSteps('Sony Store'),
  },
  {
    type: 'retailer',
    name: 'Epicentre',
    matchKeys: ['epicentre asia'],
    url: 'https://www.epicentreasia.com',
    claimSteps: retailerSteps('Epicentre'),
  },
  {
    type: 'retailer',
    name: 'Sprint-Cass',
    matchKeys: ['sprint cass'],
    url: 'https://www.sprint-cass.com',
    claimSteps: retailerSteps('Sprint-Cass'),
  },
  {
    type: 'retailer',
    name: 'Mustafa Centre',
    matchKeys: ['mustafa'],
    url: 'https://www.mustafa.com.sg',
    claimSteps: retailerSteps('Mustafa Centre'),
  },
  {
    type: 'retailer',
    name: 'Takashimaya',
    matchKeys: [],
    url: 'https://www.takashimaya.com.sg',
    claimSteps: retailerSteps('Takashimaya'),
  },
  {
    type: 'retailer',
    name: 'Tangs',
    matchKeys: [],
    url: 'https://www.tangs.com',
    claimSteps: retailerSteps('Tangs'),
  },
  {
    type: 'retailer',
    name: 'Amazon.sg',
    matchKeys: ['amazon', 'amazon sg'],
    url: 'https://www.amazon.sg/gp/help/customer/display.html',
    claimSteps: retailerSteps('Amazon.sg'),
  },
  {
    type: 'retailer',
    name: 'Lazada',
    matchKeys: ['lazada singapore'],
    url: 'https://www.lazada.sg/helpcenter/',
    claimSteps: retailerSteps('Lazada'),
  },
  {
    type: 'retailer',
    name: 'Shopee',
    matchKeys: ['shopee singapore'],
    url: 'https://help.shopee.sg/',
    claimSteps: retailerSteps('Shopee'),
  },
  {
    type: 'retailer',
    name: 'Qoo10',
    matchKeys: ['q10'],
    url: 'https://www.qoo10.sg/gmkt.inc/Help/',
    claimSteps: retailerSteps('Qoo10'),
  },
  {
    type: 'retailer',
    name: 'Best Buy',
    matchKeys: ['bestbuy'],
    url: 'https://www.bestbuy.com',
    claimSteps: retailerSteps('Best Buy'),
  },
  {
    type: 'retailer',
    name: 'Walmart',
    matchKeys: [],
    url: 'https://www.walmart.com/help',
    claimSteps: retailerSteps('Walmart'),
  },
  {
    type: 'retailer',
    name: 'Costco',
    matchKeys: [],
    url: 'https://www.costco.com/customer-service.html',
    claimSteps: retailerSteps('Costco'),
  },
];
